"""add profile birth date and weight unit

Revision ID: 7db880bfbe73
Revises: 4bda92f9e43a
Create Date: 2026-05-26 19:28:09.290439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db880bfbe73'
down_revision = '4bda92f9e43a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('weight_unit', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('weight_unit')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
